name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    env:
     NOMBRE: '${{ secrets.NOMBRE }}'
    steps:
    - uses: actions/checkout@v3
    - name: MSbuild instance setup
      uses: microsoft/setup-msbuild@v1.1
      with:
        # Version of Visual Studio to search; defaults to latest if not specified
        vs-version: 16.11.3
        # The preferred processor architecture of MSBuild. Can be either "x86" or "x64". "x64" is only available from Visual Studio version 17.0 and later.
        msbuild-architecture: x86
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Project Build
      run: msbuild envtest.sln 
    - name: execute
      run: ./envtest/bin/Debug/envtest.exe
